### ISSUE TITLE
Add details about band data values to metadata

### ISSUE THREAD

**Issue by dthiex** [eurodatacube/public-collections#224]
Add raster:bands object to collection metadata summaries.

## Example for S2-L2A B01 band

What we would need to add to the yaml files (for each band).

```yaml
  raster:bands:
    - name: B01
      data_type: float32
      statistics:
        minimum: 
          - 0
        maximum:
          - 0.4
 ```

How it will look rendered as json:

```json
"summaries": {
    "raster:bands": [
      {
        "name": "B01",
        "data_type": "float32",
        "statistics": {"minimum": 0, "maximum": 0.4}
      },
```

### Related resources:
- EDC public collections repository has the metadata in text/table form for some collections (see the `DocumentationLinks` we added to the links object)
- info about most of the core SH collections can be found in our documentation e.g. [here](https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/#units) for S2-L2A
- Info on raster STAC extension used here: https://github.com/stac-extensions/raster
- related to this request within the openEO Platform project: https://github.com/openEOPlatform/architecture-docs/issues/178#issuecomment-1006606630
